"""Gmail送信モジュール"""

import html
import smtplib
import urllib.parse
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List, Dict
from datetime import datetime


def send_digest(to: str, subject: str, html_body: str, address: str, app_password: str) -> None:
    """
    GmailのSMTPサーバー経由でHTMLメールを送信
    
    Args:
        to: 送信先メールアドレス
        subject: 件名
        html_body: HTML形式のメール本文
        address: Gmailアドレス
        app_password: Gmailアプリパスワード
    """
    try:
        # メッセージ作成
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = address
        msg['To'] = to
        
        # HTML部分を追加
        html_part = MIMEText(html_body, 'html', 'utf-8')
        msg.attach(html_part)
        
        # SMTP接続・送信
        with smtplib.SMTP('smtp.gmail.com', 587) as server:
            server.starttls()
            server.login(address, app_password)
            server.send_message(msg)
        
        print(f"Email sent successfully to {to}")
        
    except Exception as e:
        print(f"Failed to send email: {e}")
        raise


def generate_digest_html(papers_by_cluster: Dict[str, List[Dict]], config: Dict) -> str:
    """
    論文サマリーをHTML形式で生成
    
    Args:
        papers_by_cluster: クラスター別の論文リスト
        config: 設定情報
        
    Returns:
        HTML形式のメール本文
    """
    cluster_names = {
        "deployment": "🚀 Deployment",
        "use": "🔬 Use Cases", 
        "safety": "🛡️ Safety & Ethics"
    }
    
    total_papers = sum(len(papers) for papers in papers_by_cluster.values())
    
    if total_papers == 0:
        return generate_no_papers_html()
    
    body = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif; line-height: 1.6; color: #333; }}
            .container {{ max-width: 800px; margin: 0 auto; padding: 20px; }}
            .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 8px; margin-bottom: 30px; }}
            .cluster {{ margin-bottom: 40px; }}
            .cluster-title {{ font-size: 1.4em; color: #2563eb; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; margin-bottom: 20px; }}
            .paper-card {{ border: 1px solid #e5e7eb; border-radius: 8px; padding: 20px; margin-bottom: 20px; background: #fafafa; }}
            .paper-title {{ font-size: 1.1em; font-weight: 600; color: #1f2937; margin-bottom: 8px; }}
            .paper-meta {{ font-size: 0.9em; color: #6b7280; margin-bottom: 12px; }}
            .summary {{ margin-bottom: 15px; }}
            .governance-badges {{ margin-bottom: 10px; }}
            .badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.8em; margin-right: 5px; }}
            .badge-citation {{ background: #dbeafe; color: #1e40af; }}
            .badge-coi {{ background: #fef3c7; color: #92400e; }}
            .badge-retracted {{ background: #fee2e2; color: #dc2626; }}
            .links {{ font-size: 0.9em; }}
            .links a {{ color: #2563eb; text-decoration: none; margin-right: 15px; }}
            .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 0.9em; color: #6b7280; }}
            .tl-dr {{ background: #f0f9ff; border-left: 4px solid #0ea5e9; padding: 15px; margin-bottom: 30px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🏥 Medical AI Daily Digest</h1>
                <p>{datetime.now().strftime('%Y年%m月%d日')} | {total_papers}件の新着論文</p>
            </div>
            
            <div class="tl-dr">
                <h2>📋 今日のTL;DR</h2>
                {generate_tldr(papers_by_cluster)}
            </div>
    """
    
    # 各クラスターの論文を追加
    for cluster, papers in papers_by_cluster.items():
        if not papers:
            continue
            
        body += f"""
            <div class="cluster">
                <h2 class="cluster-title">{cluster_names.get(cluster, cluster)}</h2>
        """
        
        for paper in papers:
            body += generate_paper_card_html(paper)
        
        body += "</div>"
    
    # フッター
    body += f"""
            <div class="footer">
                <p><strong>免責事項:</strong> この要約は医療従事者への情報提供を目的としており、診断・治療の推奨や医学的助言を構成するものではありません。</p>
                <p>Generated by <a href="https://cursorvers.jp/tools/auditscope/">AuditScope</a> | 監査ログ: logs/audit/{datetime.now().strftime('%Y-%m-%d')}.json</p>
            </div>
        </div>
    </body>
    </html>
    """
    
    return body


def generate_paper_card_html(paper: Dict) -> str:
    """個別論文のHTMLカードを生成"""
    summary = paper.get("summary", {})
    
    # ガバナンスバッジ
    badges = []
    if summary.get("per_sentence_citations"):
        badges.append('<span class="badge badge-citation">引用付</span>')
    if summary.get("coi_extracted") and summary["coi_extracted"] != "記載なし":
        badges.append('<span class="badge badge-coi">CoI記載</span>')
    if paper.get("retraction_flag"):
        badges.append('<span class="badge badge-retracted">撤回注意</span>')
    
    badges_html = " ".join(badges)
    
    # リンク
    pmid = paper.get("pmid", "") or ""
    doi = paper.get("doi", "") or ""
    pubmed_link = f"https://pubmed.ncbi.nlm.nih.gov/{html.escape(pmid)}/" if pmid else "#"
    # DOIはURL encodeしてからHTMLエスケープ
    doi_encoded = urllib.parse.quote(doi, safe=":/.-_") if doi else ""
    doi_link = f"https://doi.org/{doi_encoded}" if doi and doi_encoded.startswith(('10.', 'doi:', 'DOI:')) else "#"
    
    # 著者リストの処理
    authors = paper.get('authors', []) or []
    if isinstance(authors, list):
        authors_str = ', '.join(str(author) for author in authors[:3])
        if len(authors) > 3:
            authors_str += '...'
    else:
        authors_str = str(authors)
    
    return f"""
        <div class="paper-card">
            <div class="paper-title">{html.escape(paper.get('title', '') or 'タイトル不明')}</div>
            <div class="paper-meta">
                {html.escape(authors_str)} | 
                {html.escape(paper.get('journal', '') or '')} ({html.escape(str(paper.get('year', '') or ''))})
            </div>
            <div class="governance-badges">{badges_html}</div>
            <div class="summary">{html.escape(summary.get('summary_3_sentences', '') or '要約なし')}</div>
            <div class="links">
                <a href="{pubmed_link}">PubMed</a>
                {f'<a href="{doi_link}">DOI</a>' if doi else ''}
                PMID: {html.escape(pmid)}
            </div>
        </div>
    """


def generate_tldr(papers_by_cluster: Dict[str, List[Dict]]) -> str:
    """TL;DRセクションを生成"""
    tldr_items = []
    
    for cluster, papers in papers_by_cluster.items():
        if papers:
            top_paper = papers[0]  # 各クラスターの最初の論文をピックアップ
            title = html.escape((top_paper.get("title", "") or "")[:80]) + "..."
            tldr_items.append(f"<li><strong>{cluster}:</strong> {title}</li>")
    
    return f"<ul>{''.join(tldr_items)}</ul>"


def generate_no_papers_html() -> str:
    """論文がない場合のHTML"""
    return f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif; line-height: 1.6; color: #333; }}
            .container {{ max-width: 600px; margin: 50px auto; padding: 40px; text-align: center; }}
            .header {{ background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 40px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>📭 Medical AI Daily Digest</h1>
                <h2>{datetime.now().strftime('%Y年%m月%d日')}</h2>
                <p>本日は検索条件に該当する新着論文はありませんでした。</p>
                <p><small>システムは正常に動作しています。</small></p>
            </div>
        </div>
    </body>
    </html>
    """